# Generated by Django 2.0.5 on 2019-01-03 11:07

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190103_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_pic',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
